### ISSUE TITLE
Odd doi switch on study creation

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1193] opened 2019-06-07 00:14 UTC
Creating a study from the url https://link.springer.com/article/10.1007/s11557-015-1098-z auto-populates a quite different paper, on sneutrinos, whatever those are (https://iopscience.iop.org/article/10.1088/1475-7516/2012/10/015/meta). It also updates the doi to the doi of this incorrect paper. 
If you create the study, and then fix the title, and search for doi, you get the correct doi.  (problem noted by @thomasstjerne )

**Comment by jimallman** [comment] 2019-06-14 16:53
We discussed this, and it seems the webapp accepts *either* a DOI or URL here, so we're probably mistaking this URL for a proper DOI. Hilarity ensues.

I'll take a closer look at this test. When in doubt, we should assume the submitted string is a URL and not a DOI.

**Comment by jar398** [comment] 2019-06-14 17:39
DOIs all start with '10.' Or 'doi:10.'

**Comment by jimallman** [comment] 2019-07-15 03:40
Understood. Nonetheless, we have assumed that a URL including `10.` has a complete DOI as the remainder of the URL. 

In this case, that's correct --`10.1007/s11557-015-1098-z` is [the DOI for a paper in _Mycological Progress_](https://search.crossref.org/?q=10.1007%2Fs11557-015-1098-z). In tracing the code, I realized that in this instance we're using [an outdated version of the search API](https://github.com/OpenTreeOfLife/phylesystem-api/blob/fd373ba3c9497f1e04d446d8478baceb3c803764/controllers/default.py#L1671) on crossref.org. Their current API [gives the expected result](https://api.crossref.org/works/10.1007%2Fs11557-015-1098-z), albeit in a more complicated wrapper. The old API works for most papers, so I'm guessing they stopped indexing new stuff to it at some point.  I'll just need to update this call to use the [new API and response format](https://github.com/CrossRef/rest-api-doc), and double-check [any other places where we call crossref.org](https://github.com/search?q=org%3AOpenTreeOfLife+%22search.crossref.org%22&type=Code) and update them as well.

**Comment by jimallman** [comment] 2019-07-19 20:22
A few other links of interest:

- Test the **latest results for a DOI** using the current [CrossRef web form](https://search.crossref.org/?q=10.1007%2Fs11557-015-1098-z)
- [CrossRef API status page](https://status.crossref.org/) (look here first, if API fails in the future)
- [API guidelines]( https://github.com/CrossRef/rest-api-doc#api-overview
) regarding whether to URL-encode slashes, etc. within a DOI _(short answer: yes)_

**Comment by jimallman** [comment] 2019-07-20 05:40
And... the plot thickens! The new API doesn't include "full citation" text, so I'll need to make a _second_ API call (probably from another provider) to fetch a formatted citation from a (confirmed) DOI. 
@snacktavish @mtholder - **What citation style is preferred for OpenTree?** I've compared the old "fullCitation" values from CrossRef, and they don't quite match any of the citation styles I can find. 
```
R. Sanders, 2001, 'A reply', <i>Anaesthesia</i>, vol. 56, no. 10, pp. 1007-1007
```
```
2014, 'Taming Heavy Grignard Reagents: Intramolecular C–F and C–H Bond Cleavage', <i>Synfacts</i>, vol. 10, no. 10, pp. 1038-1038
```
In fact, they **don't match one another**, so it's possible these were "unstructured citation strings" entered by CrossRef submitters. If this was the source for a lot of our incoming studies, it's likely we don't _have_ a consistent citation style in the current phylesystem. 

Thoughts?

**Comment by jimallman** [comment] 2019-07-20 06:02
You can [try out various citation styles](https://crosscite.org/) with any DOI if that helps make the call about a preferred style for OpenTree. 

NOTE that there is one generated text citation (style uncertain) available from the CrossRef APIs, so **that's the path of least resistance if it's acceptable**, versus adding another dependency. You can see these using the following URL pattern:
`https://api.crossref.org/works/{URL-encoded DOI}/transform/text/x-bibliography`

For example:
```bash
$ curl https://api.crossref.org/works/10.1007%2Fs11557-015-1098-z/transform/text/x-bibliography
Frøslev, T. G., Jeppesen, T. S., & Dima, B. (2015). Cortinarius koldingensis—a new species of Cortinarius, subgenus Phlegmacium related to Cortinarius sulfurinus. Mycological Progress, 14(9). doi:10.1007/s11557-015-1098-z

$ curl https://api.crossref.org/works/10.5555%2F12345678/transform/text/x-bibliography
Carberry, J. (2008). Toward a Unified Theory of High-Energy Metaphysics: Silly String Theory. Journal of Psychoceramics, 5(11), 1–3. doi:10.5555/12345678
```

**Comment by jar398** [comment] 2019-07-21 22:54
As for why styles are inconsistent, this is hardly surprising since no direction was ever given to people curating studies. So at the present time we have to assume that the reference style is unpredictable.

I think that even if direction was given, it is likely that curators would ignore it. They're just going to copy/paste whatever they have in front of them. And I'm not sure it's a good use of their time to be concerned about it - as long as they've provided a DOI.

But this is one of the many reasons that DOIs are so important and why we've put so much effort into them over the years. Given a DOI anyone can generate whatever format they like. Probably not good to do this in open tree on the fly, for performance and availability reasons, so prefetching and storing some chosen style is probably a good idea. I personally don't much care which style is stored. Your path of least resistance sounds fine to me.

Whether to do this for 'legacy' DOIs, I don't know. You may have more important things on your plate.

**Comment by jimallman** [comment] 2019-07-22 00:43
Thanks for your thoughts, @jar398 ! All very sensible. I was concerned I might have forgotten some prior discussion about citation styles. I'll press on with the CrossRef API's `x-bibliography` reference strings for now, pending a strong argument to do otherwise.

**Comment by snacktavish** [comment] 2019-07-22 17:50
That makes sense to me! We really lean on the doi, and don't do much in terms of standardization on the text citation, so the crossref return format seems fine.

**Comment by jimallman** [comment] 2019-08-02 22:31
OK, here's confirmation that we can finally handle this DOI in the latest **devtree**: https://devtree.opentreeoflife.org/curator/study/view/tt_241

(It's a good test case because of the diacritic characters in the reference text.) Testing now with invalid DOI and some other edge cases...

**Comment by jimallman** [comment] 2019-08-02 22:46
OK, I'll move on to some related bugs, e.g. the "Look up DOI..." feature in study editor uses the old CrossRef API. Shouldn't take long.

The CrossRef support team was very responsive and gave useful guidance for these fixes! Incidentally, they say the results of their `text/x-bibliography` transform should be in APA style.

**Comment by jimallman** [comment] 2019-08-05 23:32
I think that's it for outdated CrossRef API calls. If so, I suppose we can close this ticket. But it's a decent transcript of some of the background research and implementation details. (As the assignee, I'll hang back and let someone else take a look at the related PRs, then hopefully close this.)

**Comment by snacktavish** [comment] 2019-08-06 00:07
I agree that it's fixed! But lets leave this open until it's up on production.

**Comment by jimallman** [comment] 2019-09-25 19:23
OK to close this now @snacktavish ?

**Comment by snacktavish** [comment] 2019-09-25 19:43
Yes, Yay!

**Comment by snacktavish** [comment] 2020-03-16 22:09
It looks like we're running into this again on dev, and I'm not sure why! Potentially a merge somewhere dragged back up old problems?
But I tried to make a new study with the doi https://doi.org/10.1017/S0094837300006813, and it doesn't give me the right reference. 
And as a related problem it 'corrects' the DOI before creating the record, so what I actually pasted in isn't saved the metadata or the json at all.

**Comment by jimallman** [comment] 2020-03-19 15:45
> And as a related problem it 'corrects' the DOI before creating the record, so what I actually pasted in isn't saved the metadata or the json at all.

FYI, this is expected behavior. We assume that our normalization of the DOI is an improvement, or at least conforms to the rest of the study's metadata. If we want to save the raw input DOI, we'll need to add a property for it in Nexson.

**Comment by jimallman** [comment] 2020-03-19 15:45
Copying my recent updates from gitter:

> Looks like someone has deployed a branch of phylesystem-api called `streamline-update`. I can't find this branch locally or on github, but it's listed in deployed-systems as the active branch on devapi.  In any case, behavior on production is normal.
> 
> Ah, it looks like we're the culprits! :D the branch is gone, but the commits are mine and yours @snacktavish . i'll reset devapi to use the current master branch and deploy in a minute...
> -----
> OK, that fixed the new-study problem above and correctly found the sabretooth study. (I wouldn't be surprised if it fixes other quirks as well.) 

I think we can close this issue, but please re-open if I'm missing something. (If you feel strongly about saving the raw DOI-as-entered, let's make a new issue for it.)

**Closed by jimallman** 2020-03-19 15:45 UTC

**Comment by snacktavish** [comment] 2020-03-19 16:33
:+1:
