### ISSUE TITLE
Curator UI: add new trees broken when schema is NEXUS

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#542] opened 2015-01-10 20:29 UTC
this is very minor:
from a trees tab (e.g. http://tree.opentreeoflife.org/curator/study/edit/ot_237/?tab=trees ), if you:

   1. select the file to upload, then
   2. specify the schema as NEXUS

then the "Add New Tree" button remains inactive. The user has to select the file again to make the button clickable.

**Comment by jimallman** [comment] 2015-10-09 04:47
This was actually due to a quirk of the file-upload widget we're using; it **clears** the file-widget that I was using for validation. In the latest commit, I found a more stable test (scanning the inner text of the filename preview SPAN alongside) that gives the expected behavior. 

If this becomes problematic, another solution is to use the [`replacefileinput` option](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#replacefileinput), setting this to false so that the file-widget (and presumably its value) are preserved.

**Comment by jimallman** [comment] 2015-10-09 04:50
This is available for review on **devtree**. I'm closing the issue for now, since it's working for me.

**Closed by jimallman** 2015-10-09 04:50 UTC
Labels: bug
