### ISSUE TITLE
bad OTU mappings - how to help prevent?

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#769] opened 2015-09-28 21:50 UTC
https://tree.opentreeoflife.org/curator/study/edit/pg_529/?tab=trees

All taxa in the tree - I believe- belong to Hypocreales but the MRCA test (both taxonomy and synthesis) give as a result "Leotiomyceta". There are some taxa outside the Hypocreales in the study BUT not in the tree. Does the MRCA test is for the taxa in the tree or takes into account all taxa included in the study (and present in other trees)?

![screen shot 2015-09-28 at 5 45 49 pm](https://cloud.githubusercontent.com/assets/6391539/10149725/547f90d6-6609-11e5-803e-96e2b40a6630.png)

Thanks,

Romina

**Comment by rgazis** [comment] 2015-09-28 22:14
Same thing in this study but at different level

https://tree.opentreeoflife.org/curator/study/edit/pg_1669/?tab=trees
![screen shot 2015-09-28 at 6 11 57 pm](https://cloud.githubusercontent.com/assets/6391539/10150284/a79ffdac-660c-11e5-8416-0be8eebacb84.png)

And the MRCA from the taxonomy test differs in one hierarchical level than the MRCA test results from the synthetic tree

![screen shot 2015-09-28 at 6 10 17 pm](https://cloud.githubusercontent.com/assets/6391539/10150262/9381ace4-660c-11e5-9ea7-2be0eebf0c37.png)

**Comment by kcranston** [comment] 2015-09-28 22:16
The tests should only be based on the taxa in the ingroup of this tree. I agree that it is difficult to diagnose where the problem might be, though. Wonder how we might make this easier?

**Comment by rgazis** [comment] 2015-09-28 22:20
That would make sense. But, then something is not working, all the taxa in this tree 

https://tree.opentreeoflife.org/curator/study/edit/pg_1669/?tab=trees&tree=tree5902
belong to Epichloe

**Comment by jar398** [comment] 2015-09-28 22:32
We should check to make sure that the taxonomy is right before spending a
lot of time staring at the treemachine method. There is some trickiness
trying to make Hypocrea and Trichoderma be the same genus (as requested),
and perhaps I got it wrong.
Will think about how to best do this...

**Comment by jar398** [comment] 2015-09-29 00:10
I don't think it's the taxonomy.  Here's what I get when I look up the
lineages of all the OTUs in that study:

Epichloe baconii < Epichloe < Clavicipitaceae < Hypocreales
Epichloe glyceriae < Epichloe < Clavicipitaceae < Hypocreales
Epichloe typhina < Epichloe < Clavicipitaceae < Hypocreales
Epichloe festucae < Epichloe < Clavicipitaceae < Hypocreales
Epichloe elymi < Epichloe < Clavicipitaceae < Hypocreales
Epichloe clarkii < Epichloe < Clavicipitaceae < Hypocreales
Epichloe festucae < Epichloe < Clavicipitaceae < Hypocreales
Epichloe brachyelytri < Epichloe < Clavicipitaceae < Hypocreales
Claviceps fusiformis < Claviceps < Clavicipitaceae < Hypocreales
Epichloe amarillans < Epichloe < Clavicipitaceae < Hypocreales
Epichloe typhina < Epichloe < Clavicipitaceae < Hypocreales
Epichloe baconii < Epichloe < Clavicipitaceae < Hypocreales
Epichloe typhina < Epichloe < Clavicipitaceae < Hypocreales
Echinodothis tuberiformis < Dussiella < Clavicipitaceae < Hypocreales
Epichloe clarkii < Epichloe < Clavicipitaceae < Hypocreales
Epichloe brachyelytri < Epichloe < Clavicipitaceae < Hypocreales
Epichloe sylvatica < Epichloe < Clavicipitaceae < Hypocreales
Claviceps purpurea < Claviceps < Clavicipitaceae < Hypocreales
Epichloe sylvatica < Epichloe < Clavicipitaceae < Hypocreales
Epichloe typhina < Epichloe < Clavicipitaceae < Hypocreales
Epichloe amarillans < Epichloe < Clavicipitaceae < Hypocreales
Epichloe bromicola < Epichloe < Clavicipitaceae < Hypocreales
Epichloe glyceriae < Epichloe < Clavicipitaceae < Hypocreales
Epichloe elymi < Epichloe < Clavicipitaceae < Hypocreales
Epichloe typhina < Epichloe < Clavicipitaceae < Hypocreales
Epichloe bromicola < Epichloe < Clavicipitaceae < Hypocreales
Epichloe typhina < Epichloe < Clavicipitaceae < Hypocreales
Epichloe amarillans < Epichloe < Clavicipitaceae < Hypocreales

**Comment by rgazis** [comment] 2015-09-29 00:50
Here is another example, all taxa even including the outgroup, should mapped to Ascomycota but the result of the MCRA test is Eukaryota, 

https://tree.opentreeoflife.org/curator/study/edit/pg_1691/?tab=trees&tree=tree3407

**Comment by jar398** [comment] 2015-12-08 02:27
Regarding the first example, I think the problem is the classification of Paecilomyces marquandii in Index Fungorum:
```Paecilomyces marquandii(77046)
 species size:1
	(Paecilomyces marquandii 77046=if:302194) < (Paecilomyces 376367=if:9196+96) < (Trichocomaceae 5442527=if:81485+138) < (Eurotiales 800595=h2007:149+124) < (Eurotiomycetes 346124=h2007:79+134) < (Leotiomyceta 5287301=h2007:52+27) < (Pezizomycotina 971709=h2007:46+2039) < (Ascomycota 439373=h2007:40+2645) < (Division=Dikarya 5602101=h2007:27+8) < (h2007-1 5584405=h2007:11+2) ...
Synonym: Metarhizium marquandii
Synonym: Verticillium marquandii
Synonym: Verticillium marquandi
Sources: if:302194,ncbi:64636,gbif:2598113,irmng:11166067
Flags: sibling_higher```

Definitely not in Hypocreales.

**Comment by jar398** [comment] 2015-12-08 03:05
Regarding the Epichloe example, it looks like monophyly of that genus is broken by this study:

Yanagida N., Irie T., Tanaka E., Teramoto C., Kuwabara K., & Tajimi A. 2005. New choke diseases and their molecular phylogenetic analysis in Agropyron ciliare var. minus and Agropyron tsukushiense var. transiens. Mycologia, 97: 1287-1291.
Full publication: http://dx.doi.org/10.3852/mycologia.97.6.1287
Open Tree curation of this study: pg_415
Supporting tree:  tree5572

**Comment by jar398** [comment] 2015-12-08 03:12
For the study 1691 problem, the culprit is the OTU 'Baccharis epibiont' which is mapped to Baccharis, which is a plant.

If the mapping context feature had been used, this bad mapping would not have been considered.

I can find all these problems by writing little snippets of python code. I'm trying to figure out how to detect them in a general way and make them evident in the UI.

**Comment by jar398** [comment] 2015-12-09 15:08
(Comment migrated from #774 which was basically a duplicate)

Not sure how to close this issue. There are really three parts here. One of them is a 'wontfix'; if the curator expects a genus to be present in the synthetic tree, but an input tree says it's nonmonophyletic, there's little we can do other than request review of the synthesis tree list. The other two are unfortunate OTU mapping errors. I (or Romina) can go and fix the mappings, but the fact remains that the app would be much improved if we made it harder for curators to make this kind of mistake. Here are two ideas:

1. Implement #460, so at least if there is doubt, one can do a bit of research (but there is no evidence that there was doubt in this instance)
2. Make it much harder for curators to overlook or bypass the set TNRS context step
3. Put a warning in the 'fuzzy matching' documentation that it will lead to false positives, so every fuzzy match must be manually reviewed.

Number 2 might be both easier and more effective than the others.

Updating issue description.

**Comment by jar398** [comment] 2015-12-09 15:15
By the way, note that the MRCA test did exactly what it was designed to do - it allowed the curator to detect an anomaly (plant or insect taxon in a Fungi study). So that is a real success. The problem is that we have no tools for zeroing in on the cause of the anomaly.

Another thing I thought of that might help: give a way to display the tree derived from the taxonomy that is induced by the mapped OTUs. If Romina had been able to see this, the fact that the insect/plant was sister to everything else would have popped out, suggesting the possibility of a bad mapping.

**Comment by jar398** [comment] 2015-12-09 15:30
I've fixed the Baccharis epibiont mapping.

**Comment by jimallman** [comment] 2016-01-13 19:35
I should add the complication that we perform these MRCA tests using a sampling of OTUs, not all of them. **So it's possible this would miss an incorrect mapping!**

**Comment by jar398** [comment] 2016-01-26 00:53
I can think of three things we might do here.

1. Implement a feature to display the induced subtree from the taxonomy over the OTT-mapped OTUs. Outliers will show up as being very deep in the tree.

2. Provide a way to list or highlight OTUs that are outside of the 'expected focal taxon' (which is a feature we discussed as a replacement for 'focal clade'; focal clade would work in the meantime)

2. Provide a way to list potential outliers.  One can define an outlier as one that is unusually deep in the tree, i.e. the path from the root to the OTU has unusually few internal nodes. One might sort OTUs by depth, and show the top 5 or 10.

If we can decide which, I will make a new issue for the proposed feature.

**Comment by jar398** [comment] 2016-02-03 17:53
If I'm not mistaken, this issue has run its course, except for the new feature that we are discussing in #877 (which isn't about more careful auto-approval, it's about what to do after the fact if something got approved incorrectly). I think we can close this one.

**Closed by jar398** 2016-02-03 17:53 UTC
Labels: curator, needs discussion, question
