### ISSUE TITLE
Funniness in 'modified for mapping' taxon name entry

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#488] opened 2014-10-10 19:43 UTC
When I put 'Escherichia-Shigella' in the 'modified for mapping' text entry box it's not recognized as a taxon.  But it works in tree browser search box.  I don't think it's a TNRS issue; try the following, they both work.

curl -X POST http://api.opentreeoflife.org/v2/tnrs/match_names \
  -H "content-type:application/json" -d '{"names":["Escherichia-Shigella"]}'
curl -X POST http://api.opentreeoflife.org/v2/tnrs/autocomplete_name \
  -H "content-type:application/json" -d '{"name":"Escherichia-Shigella"}'

**Comment by jimallman** [comment] 2015-01-01 03:27
Confirmed in latest **devtree**. This name is only matched if "Use fuzzy matching" is enabled in the curation app. Here's the request payload:
```json
{
  "queryString":"Escherichia-Shigella",
  "includeDubious":false,
  "includeDeprecated":false,
  "doApproximateMatching":true,
  "contextName":"All life"
}
```
...and here's the response:
```json
{
  "governing_code" : "undefined",
  "unambiguous_name_ids" : [ ],
  "unmatched_name_ids" : [ ],
  "matched_name_ids" : [ "Escherichia-Shigella" ],
  "context" : "All life",
  "includes_deprecated_ids" : false,
  "includes_dubious_names" : false,
  "includes_approximate_matches" : true,
  "taxonomy" : {
    "author" : "open tree of life project",
    "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
    "source" : "ott2.8"
  },
  "results" : [ {
    "id" : "Escherichia-Shigella",
    "matches" : [ {
      "is_deprecated" : false,
      "dubious_name" : false,
      "is_synonym" : false,
      "flags" : [ ],
      "search_string" : "escherichia\\-shigella",
      "score" : 0.85,
      "is_approximate_match" : true,
      "ot:ottId" : 5248878,
      "matched_node_id" : 307523,
      "rank" : "",
      "matched_name" : "Escherichia-Shigella",
      "unique_name" : "Escherichia-Shigella",
      "nomenclature_code" : "ICNP",
      "ot:ottTaxonName" : "Escherichia-Shigella"
    } ]
  } ]
}
```
This looks like an exact match, but I see that `search_string` has an escaped hyphen. Perhaps this is distorting our results and creating a fuzzy match instead?

I don't see anyplace in Javascript where we encode/escape this hyphen, and it doesn't appear when I save this call as cURL in Chrome's dev tools:

I suspect it's happening en route to [the `contextQuery` method of taxomachine's TNRS plugin](https://github.com/OpenTreeOfLife/taxomachine/blob/64752a337e3a253f893b3d82b699c7da93d0ae56/src/main/java/org/opentree/taxonomy/plugins/TNRS.java#L237-L348)?

@chinchliff, @josephwb: Does this seem likely? In the code linked above, should we be unescaping (decoding) search strings in `idNameMap` before passing them into our `MultiNameContextQuery`?

**Comment by mtholder** [comment] 2015-01-08 14:54
My guess would be that it is [the `escape` call here](https://github.com/OpenTreeOfLife/taxomachine/blob/64752a337e3a253f893b3d82b699c7da93d0ae56/src/main/java/org/opentree/tnrs/queries/MultiNameContextQuery.java#L83) that is causing us problems.

It looks like the dash is reserved in lucene query (see http://lucene.apache.org/core/3_0_3/api/all/org/apache/lucene/queryParser/QueryParser.html ). My guess would be that our explicit escape is adding the \ (on the same line in which it changes to lower case), and then we are using some function that does not parse the query via Lucene (and hence does not need lucene's escaping).

It think that we use a neo4j Index<Node> (called nameIndex) to check for exact matches. Because we escape the string too early, we aren't getting the hit there.  If that is correct, we just need to move to lazy escaping of strings until right before we call a lucene function (or a separate data member for the escaped and unescaped strings)

**Comment by jimallman** [comment] 2015-10-08 15:57
@mtholder, it looks like this is still a problem. I reproduced the original situation above; without fuzzy matching, 'Escherichia-Shigella' is not found when mapping OTUs. I'm closing this issue, but have created [a new one in taxomachine](https://github.com/OpenTreeOfLife/taxomachine/issues/101) to keep this on our radar.

**Closed by jimallman** 2015-10-08 15:57 UTC
Labels: bug
