### ISSUE TITLE
Importing tree file doesn't like taxon names like this 'Bembidion (Notholopha) sp. 1'

### ISSUE THREAD

**Issue by DMaddison** [OpenTreeOfLife/opentree#1023] opened 2016-08-15 18:08 UTC
Importing a tree file with this taxon name: 'Bembidion (Notholopha) sp. 1' caused importing to fail.  It also gave a non-informative error message.

**Comment by mtholder** [comment] 2016-08-15 20:28
fixed in NCL - it was actually a core dump caused by some but not all edges having lengths. 
Fixed and deployed.

**Closed by mtholder** 2016-08-15 20:28 UTC
