### ISSUE TITLE
Duplicate study from treebase should be detected early

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#485] opened 2014-10-09 22:57 UTC
If I import a study from treebase, and it's a duplicate of one that's already in phylesystem, it would be nice to get a notification at the point of the import, before OTU mapping and so on.
Duplicates can be detected either on the basis of DOI/URL (more important) or data deposit DOI/URL (less important but about 50% of treebase entries lack DOIs).

Along the same lines, if you look up a DOI using the wonderful DOI lookup feature, and it turns out to be a duplicate, then it would be good to get a warning there as well.

**Comment by kcranston** [comment] 2015-04-13 19:49
Duplicate of issue #300

**Closed by kcranston** 2015-04-13 19:49 UTC
