### ISSUE TITLE
Fungal species in IF not in OTT - described in 2007

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#731] opened 2015-08-31 18:07 UTC
Species: Megalohypha aqua-dulces
Study
https://tree.opentreeoflife.org/curator/study/edit/ot_368/?tab=otu-mapping

http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=505742

**Comment by pmidford** [comment] 2015-08-31 18:56
I recall something funny about this species (perhaps inconsistency in
the hyphanation between two files) in the files Paul Kirk provided.  It
may be something easy to fix.

**Comment by jar398** [comment] 2015-08-31 23:59
Looks to me as if it's in OTT 2.8:

1078779 | 908797 | Megalohypha aqua-dulces | species |
if:505742,ncbi:435401,gbif:2611198 | | |

Maybe a problem with treatment of hyphens in the TNRS and/or curator app?

**Comment by rgazis** [comment] 2015-09-01 18:18
Another hyphen-taxa not recognized by OTT mapping

Colletotrichum jasmini-sambac
https://tree.opentreeoflife.org/curator/study/edit/ot_388/?tab=otu-mapping
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=518491

**Comment by jar398** [comment] 2015-09-01 18:52
These are both in OTT 2.8
136956 | 376122 | Armillaria novae-zelandiae | species |
if:308929,ncbi:153914,gbif:2536855,irmng:10386606,irmng:10781661 | | |
724489 | 1085553 | Colletotrichum jasmini-sambac | species |
if:518491,ncbi:1185849 | | sibling_lower |

The next step is to localize the bug (taxomachine vs. curator).

**Comment by jar398** [comment] 2015-09-02 13:31
(Mainly for @jimallman :) 

The API seems to be doing the right thing (except that the search_string has a backslash in it; that seems wrong to me but I don't know the semantics of that field; and anyhow I doubt anyone looks at that value). That would suggest the problem is in the curator app. Here is an example.

curl -X POST http://api.opentreeoflife.org/v2/tnrs/match_names \
-H "content-type:application/json" -d \
'{"names":["Colletotrichum jasmini-sambac"]}'
> > {
  "governing_code" : "undefined",
  "unambiguous_name_ids" : [ ],
  "unmatched_name_ids" : [ ],
  "matched_name_ids" : [ "Colletotrichum jasmini-sambac" ],
  "context" : "All life",
  "includes_deprecated_taxa" : false,
  "includes_dubious_names" : false,
  "includes_approximate_matches" : true,
  "taxonomy" : {
    "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
    "author" : "open tree of life project",
    "source" : "ott2.8"
  },
  "results" : [ {
    "id" : "Colletotrichum jasmini-sambac",
    "matches" : [ {
      "matched_node_id" : 542992,
      "synonyms" : [ "Colletotrichum jasmini-sambac", "Colletotrichum jasminisambac" ],
      "flags" : [ "SIBLING_LOWER" ],
      "ot:ottTaxonName" : "Colletotrichum jasmini-sambac",
      "search_string" : "colletotrichum jasmini\\-sambac",
      "matched_name" : "Colletotrichum jasmini-sambac",
      "is_synonym" : false,
      "score" : 0.9310344827586207,
      "unique_name" : "Colletotrichum jasmini-sambac",
      "ot:ottId" : 724489,
      "is_deprecated" : false,
      "nomenclature_code" : "ICN",
      "is_approximate_match" : true,
      "rank" : "",
      "is_dubious" : false
    }, {
      "matched_node_id" : 542992,
      "synonyms" : [ "Colletotrichum jasmini-sambac", "Colletotrichum jasminisambac" ],
      "flags" : [ "SIBLING_LOWER" ],
      "ot:ottTaxonName" : "Colletotrichum jasmini-sambac",
      "search_string" : "colletotrichum jasmini\\-sambac",
      "matched_name" : "Colletotrichum jasminisambac",
      "is_synonym" : true,
      "score" : 0.8928571428571429,
      "unique_name" : "Colletotrichum jasmini-sambac",
      "ot:ottId" : 724489,
      "is_deprecated" : false,
      "nomenclature_code" : "ICN",
      "is_approximate_match" : true,
      "rank" : "",
      "is_dubious" : false
    } ]
  } ]
}

**Comment by jimallman** [comment] 2015-09-02 14:27
Regarding the backslash:
```json
"search_string" : "colletotrichum jasmini\-sambac",
```
This is probably used as a regular expression in the TNRS, so escaping the hyphen so that it's not interpreted as a range specifier, as in ```[a-z]```.

**Comment by jimallman** [comment] 2015-09-02 14:57
On further investigation, it looks like the escaping (mentioned above) is added by the TNRS, but then it confuses the search results. 

When I try the [OTU mapping at the URL above](https://tree.opentreeoflife.org/curator/study/edit/ot_368/?tab=otu-mapping), it fails to map 'Colletotrichum jasmini-sambac' until I turned on **fuzzy matching**, at which point it returns the expected result but as a "93% match", apparently due to the escaped hyphen character. (For comparison, search for 'Colletotrichum jasminisambac' to see a 100% match on the unhyphenated synonym.)

Digging into the TNRS code, I see that the search string is [passed to Lucene for escaping](https://github.com/OpenTreeOfLife/taxomachine/blob/64752a337e3a253f893b3d82b699c7da93d0ae56/src/main/java/org/opentree/tnrs/queries/MultiNameContextQuery.java#L83), and that `QueryParser.escape` [does include hyphens among the characters to be escaped](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Escaping Special Characters).

This doesn't seem very smart about detecting whether such characters **should** be escaped or treated literally in any given instance. Instead, [this discussion on StackOverflow](http://stackoverflow.com/questions/263081/how-to-make-the-lucene-queryparser-more-forgiving) recommends that we try searching on the literal input first, then (in the event of a ParseError) fall back to the escaped version. I believe this approach will give the results we want.

**Comment by jimallman** [comment] 2015-09-02 15:00
That said, I'm not sure who is the right person to try this (@josephwb?). In the meantime, @rgazis and others can use the **fuzzy matching** feature to see the expected result.

**Comment by jar398** [comment] 2015-12-10 16:39
Closing the issue here in favor of tracking in taxomachine repo:
https://github.com/OpenTreeOfLife/taxomachine/issues/119

**Closed by jar398** 2015-12-10 16:39 UTC
